# origins is a list of public github repos
origins:
    # example
    # owner is the github owner
    # repo is the name of the github repo
    # - owner: <owner>
    # repo : <repo>
  - owner: temporalio
    repo: go-samples

# target is the local dir where the tool will look for files to write snippets to
# default is docs
target: docs
